"""Alias helpers."""

import re
from typing import Optional

_PAREN = re.compile(r"\s*\([^)]*\)\s*")
_PUNCT_WS = re.compile(r"[^a-z0-9+]+")


def _slug(s: str) -> str:
    s = _PAREN.sub(" ", (s or "").lower())
    return _PUNCT_WS.sub("", s)


def _strip_paren(s: str) -> str:
    """Strip trailing parenthesized qualifiers: 'Sentinel-2 (SatlasPretrain)' -> 'Sentinel-2'."""
    return _PAREN.sub(" ", s or "").strip()


DATASET_ALIASES: dict[str, str] = {
    _slug(raw): canonical
    for raw, canonical in {
        "AIR-POLSAR-SEG": "AIR-PolSAR-Seg",
        "AIR-PolSAR-Seg": "AIR-PolSAR-Seg",
        "BreizhCrops": "BreizhCrops",
        "Breizhcrops": "BreizhCrops",
        "Chesapeake Land Cover": "Chesapeake-LandCover",
        "Chesapeake Landcover": "Chesapeake-LandCover",
        "DeepGlobe": "DeepGlobe-LandCover",
        "DeepGlobe Land Cover Classification": "DeepGlobe-LandCover",
        "DeepGlobe Land Cover Classification Dataset": "DeepGlobe-LandCover",
        "Dyna-MM": "DynamicEarthNet-MM",
        "Dyna.-MM": "DynamicEarthNet-MM",
        "Dyna-Pla": "DynamicEarthNet-Pla",
        "Dyna.-Pla.": "DynamicEarthNet-Pla",
        "Dyna.-pla": "DynamicEarthNet-Pla",
        "Dyna-S2": "DynamicEarthNet-S2",
        "EnMAP-CORINE": "EnMAP-Corine",
        "EnMAP-Corine": "EnMAP-Corine",
        "FAIR1M-v1.0": "FAIR1M-v1.0",
        "FLAIR #1": "FLAIR-1",
        "FLAIR#1": "FLAIR-1",
        "FLAIR-1": "FLAIR-1",
        "FLAIR #2": "FLAIR-2",
        "FLAIR#2": "FLAIR-2",
        "FLAIR-2": "FLAIR-2",
        "GID-15": "GID-15",
        "GID15": "GID-15",
        "GeoNRW": "GeoNRW",
        "GEONRW": "GeoNRW",
        "HLS Burn Scar": "HLS-BurnScars",
        "HLS Burn Scars": "HLS-BurnScars",
        "HLS Burn Scars dataset": "HLS-BurnScars",
        "hls_burn_scars": "HLS-BurnScars",
        "NeonTree": "NeonTree",
        "NEON Tree": "NeonTree",
        "Onera Satellite Change Detection": "OSCD",
        "RSC11": "RSC11",
        "RS C11": "RSC11",
        "RSI-CB": "RSI-CB",
        "RSI CB": "RSI-CB",
        "SARDet-100K": "SARDet-100K",
        "SARDet-100k": "SARDet-100K",
        "SA-Crop-Type": "SA-Crop-Type",
        "SA Crop Type": "SA-Crop-Type",
        "SAcrop3k": "SA-Crop-Type",
        "So2Sat LCZ-42": "So2Sat-LCZ42",
        "So2Sat-LCZ42": "So2Sat-LCZ42",
        "SoSAT-LCZ42": "So2Sat-LCZ42",
        "UAVID": "UAVid",
        "UAVid": "UAVid",
        "UCM Caption": "UCM-Captions",
        "UCM-caption": "UCM-Captions",
        "UCM-Captions": "UCM-Captions",
        "SkyScript classification dataset": "SkyScript-classification",
        "SkyScript-classification": "SkyScript-classification",
        "Functional Map of the World RGB training set": "fMoW-RGB",
        "fMoW - RGB version": "fMoW-RGB",
        "ImageNet": "ImageNet-1K",
        "ImageNet-1K": "ImageNet-1K",
        "Major-TOM": "MajorTOM-Core",
        "Major TOM": "MajorTOM-Core",
        "MajorTOM": "MajorTOM-Core",
        "Harmonized Landsat Sentinel-2": "HLS",
        "NASA Harmonized Landsat Sentinel-2": "HLS",
        "Harmonized Landsat Sentinel-2 (HLS)": "HLS",
        "SatlasPretrain Sentinel-1 subset": "SatlasPretrain",
        "SeCo dataset": "SeCo",
        "SeCo-100K": "SeCo",
        "SSL4EO": "SSL4EO-S12",
        "SSL4EO-S12-ML": "SSL4EO-S12",
        "Inria Aerial Image Labeling": "InriaAerial",
        "INRIA Aerial Image": "InriaAerial",
        "INRIA Aerial Image Labeling": "InriaAerial",
        "MillionAID": "MillionAID",
        "Million-AID": "MillionAID",
        "million-AID": "MillionAID",
        "NWPU-RESISC45": "NWPU-RESISC45",
        "NWPU RESISC45": "NWPU-RESISC45",
        "NWPU-RESISC-45": "NWPU-RESISC45",
        "NWPU RESISC-45": "NWPU-RESISC45",
        "RESISC-45": "NWPU-RESISC45",
        "RESISC45": "NWPU-RESISC45",
        "NWPU-RESISC": "NWPU-RESISC45",
        "UCMerced": "UCMerced",
        "UC Merced": "UCMerced",
        "UC-Merced": "UCMerced",
        "UCM": "UCMerced",
        "UCMerced-LandUse": "UCMerced",
        "UC Merced Land Use": "UCMerced",
        "UC Merced Land Use Dataset": "UCMerced",
        "UC Merced Land-Use Dataset": "UCMerced",
        "UC Merced Land Use (UCM)": "UCMerced",
        "UCM-Classification": "UCMerced",
        "Potsdam": "Potsdam",
        "ISPRS Potsdam": "Potsdam",
        "Vaihingen": "Vaihingen",
        "ISPRS Vaihingen": "Vaihingen",
        "iSAID": "iSAID",
        "IsAID": "iSAID",
        "isAID": "iSAID",
        "fMoW": "fMoW",
        "FMoW": "fMoW",
        "Functional Map of the World (fMoW)": "fMoW",
        "Functional Map of the World (FMoW)": "fMoW",
        "fMoW-RGB": "fMoW-RGB",
        "fMoW RGB": "fMoW-RGB",
        "FMoW-RGB": "fMoW-RGB",
        "fMoW-Sentinel": "fMoW-Sentinel",
        "fMoW Sentinel": "fMoW-Sentinel",
        "fMoW-sentinel": "fMoW-Sentinel",
        "fMoW-S2": "fMoW-Sentinel",
        "BigEarthNet": "BigEarthNet-S2",
        "BigEarthNet-S2": "BigEarthNet-S2",
        "BEN-S2": "BigEarthNet-S2",
        "BigEarthNet-MM": "BigEarthNet-MM",
        "BEN-MM": "BigEarthNet-MM",
        "BigEarthNet-S1": "BigEarthNet-S1",
        "BigEarthNet-SAR": "BigEarthNet-S1",
        "SEN12MS": "Sen12MS",
        "Sen12MS": "Sen12MS",
        "EuroSAT": "EuroSAT",
        "EuroSat": "EuroSAT",
        "DOTA": "DOTA",
        "DOTA-V1.0": "DOTA-v1.0",
        "DOTA V1": "DOTA-v1.0",
        "DOTA-v1.5": "DOTA-v1.5",
        "DOTA V1.5": "DOTA-v1.5",
        "DOTA-V2.0": "DOTA-v2.0",
        "DOTA-v2.0": "DOTA-v2.0",
        "DOTA v2.0": "DOTA-v2.0",
        "DOTA2.0": "DOTA-v2.0",
        "DOTA V2": "DOTA-v2.0",
        "SpaceNet": "SpaceNet",
        "SpaceNetv1": "SpaceNet-v1",
        "SpaceNet v1": "SpaceNet-v1",
        "SpaceNet1": "SpaceNet-v1",
        "SpaceNet2": "SpaceNet-v2",
        "SpaceNet7": "SpaceNet-v7",
        "SpaceNet 7": "SpaceNet-v7",
        "SpaceNet 6": "SpaceNet-v6",
        "RSVQA-LR": "RSVQA-LR",
        "RSVQA LR": "RSVQA-LR",
        "RSVQA-LRBEN": "RSVQA-LR",
        "RSVQA-HR": "RSVQA-HR",
        "RSVQA HR": "RSVQA-HR",
        "RSVQA-HRBEN": "RSVQA-HR",
        "OPTIMAL-31": "OPTIMAL-31",
        "OPTIMAL31": "OPTIMAL-31",
        "Optimal-31": "OPTIMAL-31",
        "FAIR1M": "FAIR1M",
        "FAIR-1M": "FAIR1M",
        "FAIR1M-2.0": "FAIR1M-v2.0",
        "FAIR1M1.0": "FAIR1M-v1.0",
        "NWPU VHR-10": "NWPU-VHR-10",
        "NWPU-VHR10": "NWPU-VHR-10",
        "NWPU-VHR-10": "NWPU-VHR-10",
        "NWPUVHR-10": "NWPU-VHR-10",
        "NWPUVHR10": "NWPU-VHR-10",
        "SIRI-WHU": "SIRI-WHU",
        "SIRI WHU": "SIRI-WHU",
        "WHU-RS19": "WHU-RS19",
        "WHU RS19": "WHU-RS19",
        "HRSC2016": "HRSC2016",
        "HRSC": "HRSC2016",
        "LEVIR": "LEVIR",
        "Levir": "LEVIR",
        "LEVIR-CD": "LEVIR-CD",
        "LEVIR-CD+": "LEVIR-CD+",
        "Levir_CS": "LEVIR-CS",
        "Levir CS": "LEVIR-CS",
        "NaSC-TG2": "NaSC-TG2",
        "NaSC TG2": "NaSC-TG2",
        "RSI-CB256": "RSI-CB256",
        "RSI-CB-256": "RSI-CB256",
        "Sydney-Captions": "Sydney-Captions",
        "Sydney Captions": "Sydney-Captions",
        "Xiongan": "Xiongan",
        "XiongAn": "Xiongan",
        "xView": "xView",
        "Xview": "xView",
        "Massachusetts Buildings": "Massachusetts-Buildings",
        "Massachusetts Roads": "Massachusetts-Roads",
        "RSSCN7": "RSSCN7",
        "So2Sat": "So2Sat",
        "m-eurosat": "m-EuroSAT",
        "m-EuroSat": "m-EuroSAT",
        "m-EuroSAT": "m-EuroSAT",
        "m-bigearthnet": "m-BigEarthNet",
        "m-BigEarthNet": "m-BigEarthNet",
        "m-so2sat": "m-So2Sat",
        "m-So2Sat": "m-So2Sat",
        "m-SO2SAT": "m-So2Sat",
        "m-forestnet": "m-ForestNet",
        "m-ForestNet": "m-ForestNet",
        "m-brick-kiln": "m-Brick-Kiln",
        "m-Brick-Kiln": "m-Brick-Kiln",
        "m-SA-crop-type": "m-SA-Crop-Type",
        "m-SA-Crop-Type": "m-SA-Crop-Type",
        "m-cashew-plant": "m-Cashew-Plantation",
        "m-cashewplant": "m-Cashew-Plantation",
        "m-Cashew-Plant": "m-Cashew-Plantation",
        "m-cashew-plantation": "m-Cashew-Plantation",
        "m-pv4ger": "m-PV4GER",
        "m-PV4GER": "m-PV4GER",
        "m-pv4ger-seg": "m-PV4GER-Seg",
        "m-NeonTree": "m-NeonTree",
        "m-nz-cattle": "m-NZ-Cattle",
        "m-chesapeake-landcover": "m-Chesapeake-Landcover",
        "PASTIS": "PASTIS",
        "PASTIS-HD": "PASTIS-HD",
        "PASTIS-MM": "PASTIS-MM",
        "PASTIS-R": "PASTIS-R",
        "TreeSatAI": "TreeSatAI",
        "TreeSatAI-TS": "TreeSatAI-TS",
        "Landsat-8": "Landsat-8",
        "Landsat 8": "Landsat-8",
        "Landsat-7": "Landsat-7",
        "Landsat-9": "Landsat-9",
        "SOTA": "SAMRS-SOTA",
        "SIOR": "SAMRS-SIOR",
        "FAST": "SAMRS-FAST",
        "SAMRS": "SAMRS",
        "LAION-400M": "LAION-400M",
        "LAION400M": "LAION-400M",
        "VisDrone": "VisDrone",
        "Visdrone": "VisDrone",
        "World Cereal": "WorldCereal",
        "WorldCereal": "WorldCereal",
        "SatlasPretrain": "SatlasPretrain",
        "SATLASPRETRAIN": "SatlasPretrain",
        "Satlas": "Satlas",
    }.items()
}
SENSOR_CANONICAL: set[str] = {
    "Sentinel-1",
    "Sentinel-2",
    "Sentinel-3",
    "Landsat",
    "Landsat-5",
    "Landsat-7",
    "Landsat-8",
    "Landsat-9",
    "MODIS",
    "SPOT",
    "SPOT-6",
    "SPOT-7",
    "SPOT-6/7",
    "Gaofen",
    "Gaofen-1",
    "Gaofen-2",
    "NAIP",
    "Aerial",
    "ALOS",
    "ALOS-2",
    "WorldView",
    "Planet",
    "VIIRS",
    "SAR",
    "Optical",
    "Multispectral",
    "RGB",
}

_SENSOR_SLUGS: set[str] = {_slug(s) for s in SENSOR_CANONICAL}
ALWAYS_EXCLUDE_DATASETS: set[str] = {
    "Quach et al. [43] wave height regression dataset",
    "Stopa et al. [52] air temperature regression dataset",
    "Wang et al. [61] labelled ocean SAR imagery dataset",
    "Haiti development survey tasks from Head et al. 2017",
    "Nepal development survey tasks from Head et al. 2017",
    "Rwanda development survey tasks from Head et al. 2017",
    "A compilation of global bio-optical in situ data for ocean-colour satellite applications - version 3",
    "A database of ocean primary productivity from the 14C method",
    "Bermuda Atlantic Time-Series Study (BATS) primary production",
    "Bermuda Atlantic Time-Series Study primary production",
    "California Current Ecosystem LTER primary production estimates from 14C uptake",
    "Combined constraints on global ocean primary production using observations and models",
    "Global marine phytoplankton production dataset",
    "Germany crop type dataset from Rußwurm and Körner",
    "France crop type dataset from RPG",
    "GeoChat single-image benchmarks",
    "Custom 7-class remote sensing scene classification dataset",
    "custom Sat2Cap test split",
    "custom loci classification dataset",
    "custom OpenStreetMap-based classification dataset",
    "cropland mapping benchmarks",
    "multi-temporal crop segmentation dataset",
    "Live Fuel Moisture Content",
    "live fuel moisture dataset",
    "Airport",
    "Mosaic",
    "Mangrove",
    "Farmland",
    "Woody",
    "River",
    "Spekboom",
}
DOWNSTREAM_EXCLUDE_DATASETS: set[str] = {
    "NLCD",
    "NLCD-L",
    "CDL",
    "Cropland Data Layer",
    "Cropland Data Layer (CDL)",
    "USDA Cropland Data Layer (CDL)",
    "ESA WorldCover v200",
    "ESRI land cover maps",
    "Hansen Global Forest Change",
    "MERRA-2",
    "ERA5",
    "EURO-CORDEX",
    "CORDEX-CMIP5-RCP8.5",
    "ODIAC",
    "GEDI-L4A",
    "AVIRIS",
    "ASTER GED",
    "ASTER GED (surface emissivity)",
    "AmeriFlux",
    "FLUXNET",
    "ICOS",
    "SMAP",
    "HURDAT",
    "MTBS historical fire database",
    "Monitoring Trends in Burn Severity",
    "Monitoring Trends in Burn Severity (MTBS)",
    "Burned Area Emergency Response",
    "Burned Area Emergency Response (BAER)",
    "CalFire",
    "OpenET ensemble",
    "OpenET ensemble (evapotranspiration)",
    "ZTRAX",
    "TIGER/Line Geodatabases",
    "WorldPop",
    "Gridded Population of the World, Version 4",
    "VIIRS Day/Night Band Nighttime Lights",
    "CIA World Factbook",
    "GLaNCE land cover",
    "Descals oil palm",
    "AWS Terrain Tiles",
    "LUCAS",
    "LUCAS land cover",
    "LUCAS land use",
    "LCMAP land cover",
    "LCMAP land use",
    "LCMAP land cover change",
    "LCMAP land use change",
    "Corine [MODIS]",
    "Corine [SuperDove]",
    "MajorTOM-LUCAS-2018",
    "CloudSat/CALIPSO vertical cloud masks",
    "GOES-ABI 14-channel image chips",
    "2015 American Community Survey",
    "Uganda Living Standards Measurement Study",
    "Uganda Living Standards Measurement Study (LSMS)",
    "Air Temperature",
    "Elevation",
    "Population Density",
    "Median Income",
    "Countries",
    "Ecoregions",
    "California Housing",
    "Texas Housing",
    "MajorTOM-Core",
    "ImageNet-1K",
    "fMoW-temporal",
    "ben-ge-8k",
    "BigEarthNet20k",
    "reBEN-S1",
    "reBEN-S2",
    "MultiEarth",
    "EarthView",
    "EarthView (NEON)",
    "MOSAIKS",
    "RapidAI4EO",
    "PANGAEA",
    "PhilEO",
    "PhilEO Bench",
    "SatlasPretrain",
    "SAMRS",
    "iNat",
    "iNat2017",
    "iNaturalist 2018",
    "NABirds",
    "BirdSnap",
    "NUS-WIDE",
    "SUN-RGBD",
    "NYU-Depth v2",
    "YFCC100M-GEO100",
    "BHP Watertanks",
    "South Africa Crop Type Mapping dataset",
    "Ghana dataset from Radiant Earth Foundation",
    "South Sudan dataset from Radiant Earth Foundation",
    "Crop Type Mapping dataset",
    "Crop Type Mapping dataset (South Sudan)",
    "Crop Type Mapping-SS",
}
PRETRAIN_EXCLUDE_DATASETS: set[str] = {
    "Custom Google Earth global multi-resolution dataset",
    "Custom curated multi-temporal Sentinel-2 unchanged-regions dataset",
    "Custom multi-sensor dataset",
    "Curated multi-modal RSI dataset",
    "Global Dataset",
    "Google Static Maps API imagery",
    "RingMo-style multi-modal dataset",
    "SkySense pretraining dataset",
    "DETR pretraining dataset",
    "DiffusionSat pretraining data",
    "Depth Anything v2 corpus",
    "augmented OSCD subsets",
    "custom Central Andes pretraining dataset",
    "custom Sentinel-2 pretraining dataset",
    "custom aerial remote sensing pretraining dataset compiled from multiple collected open-source airborne remote sensing datasets",
    "custom coterminous image triplets from Airbus SPOT",
    "custom dataset from Baidu Map API",
    "custom global pretraining dataset constructed following the Dynamic World sampling strategy",
    "custom globally sampled pretraining dataset",
    "custom large-scale unlabeled remote sensing dataset collected using Google Earth Engine",
    "custom visible remote sensing image dataset",
    "target bi-temporal scenes",
    "target bi-temporal scenes only",
    "Sentinel-1 Wave Mode image archive",
    "Sentinel-2 L2A unlabeled dataset over France",
    "Sentinel-3 A and B L2 OLCI full resolution water reflectances",
    "MOD021KM MODIS/Terra Calibrated Radiances 5-Min L1B Swath 1km",
    "Worldview-2 Shenzhen bitemporal scene",
}

_ALWAYS_EXCLUDE_SLUGS: set[str] = {_slug(s) for s in ALWAYS_EXCLUDE_DATASETS}
_DOWNSTREAM_EXCLUDE_SLUGS: set[str] = {_slug(s) for s in DOWNSTREAM_EXCLUDE_DATASETS}
_PRETRAIN_EXCLUDE_SLUGS: set[str] = {_slug(s) for s in PRETRAIN_EXCLUDE_DATASETS}


def norm_dataset(raw: str, context: str = "downstream") -> Optional[str]:
    """Return the canonical dataset label for ``raw`` or None.

    ``context="downstream"`` (default) excludes ALWAYS_EXCLUDE and
    DOWNSTREAM_EXCLUDE — appropriate when normalizing held-out benchmarks.
    ``context="pretrain"`` excludes ALWAYS_EXCLUDE and PRETRAIN_EXCLUDE —
    drops generic descriptors (``"custom Sentinel-2 pretraining dataset"``)
    that aren't *named* corpora, while keeping real pretraining sources
    (ImageNet-1K, MERRA-2, SatlasPretrain) that we exclude on the
    downstream side.
    """
    if not raw:
        return None
    key = _slug(raw)
    if not key:
        return None
    if key in _ALWAYS_EXCLUDE_SLUGS:
        return None
    if context == "downstream" and key in _DOWNSTREAM_EXCLUDE_SLUGS:
        return None
    if context == "pretrain" and key in _PRETRAIN_EXCLUDE_SLUGS:
        return None
    if key in DATASET_ALIASES:
        return DATASET_ALIASES[key]
    stripped = _strip_paren(raw)
    if stripped != raw:
        key2 = _slug(stripped)
        if key2 in _ALWAYS_EXCLUDE_SLUGS:
            return None
        if context == "downstream" and key2 in _DOWNSTREAM_EXCLUDE_SLUGS:
            return None
        if context == "pretrain" and key2 in _PRETRAIN_EXCLUDE_SLUGS:
            return None
        if key2 in DATASET_ALIASES:
            return DATASET_ALIASES[key2]
    return stripped or raw.strip()


def is_sensor_only(raw: str) -> bool:
    """True iff ``raw`` is a bare sensor / satellite stream label."""
    if not raw:
        return False
    if _slug(raw) in _SENSOR_SLUGS:
        return True
    stripped = _strip_paren(raw)
    return stripped != raw and _slug(stripped) in _SENSOR_SLUGS


def canonical_slug(raw: str) -> Optional[str]:
    """Slug of the canonical name (safe for alias-aware Counter keys)."""
    c = norm_dataset(raw)
    return _slug(c) if c else None
